=== RR-593/group33/_data/schemas/shelf.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "shelf.schema.json",
  "title": "Shelf",
  "type": "object",
  "required": ["title", "description", "image", "artifacts"],
  "additionalProperties": false,
  "properties": {
    "title": { "$ref": "#/$defs/text" },
    "description": { "$ref": "#/$defs/text" },
    "image":  { "$ref": "#/$defs/image" },
    "artifacts": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/$defs/artifact" }
    }
  },


  "$defs": {


    "text": { "type": "string", "minLength": 1 },


    "artifact": {
      "type": "object",
      "required": ["description", "metaDescription", "images", "audioDescription"],
      "additionalProperties": false,
      "properties": {
        "description": { "$ref": "#/$defs/text" },
        "metaDescription": { "$ref": "#/$defs/metaDescription" },
        "images": {
          "type": "array", 
          "minItems":1, 
          "items": { "$ref": "#/$defs/image" }
        },
        "obj3D": { "$ref": "#/$defs/object3D" },
        "audioDescription": { "$ref": "#/$defs/audioDescription" }
      }
    },

    "dimension": {
      "type" : "array", 
      "minItems": 3,
      "maxItems": 3,
      "items": {"type": "number"}
    },


    "metaDescription": {
      "type": "object",
      "required": ["name", "accNo", "material", "dimension", "details"],
      "additionalProperties": false,
      "properties": {
        "name": { "$ref": "#/$defs/text" },
        "accNo": { "$ref": "#/$defs/text" },
        "material": { "$ref": "#/$defs/text" },
        "dimension": { "$ref": "#/$defs/dimension" },
        "details": { "$ref": "#/$defs/text" }
      }
    },


    "image": {
      "type": "object",
      "required": ["url", "altText", "caption"],
      "additionalProperties": false,
      "properties": {
        "url": { "$ref": "#/$defs/text" },
        "altText": { "$ref": "#/$defs/text" },
        "caption": { "$ref": "#/$defs/text" }
      }
    },


    "object3D": {
      "type": "object",
      "required": ["url", "altText"],
      "additionalProperties": false,
      "properties": {
        "url": { "$ref": "#/$defs/text" },
        "altText": { "$ref": "#/$defs/text" }
      }
    },


    "audioDescription": {
      "type": "object",
      "required": ["url", "transcript"],
      "additionalProperties": false,
      "properties": {
        "url": { "$ref": "#/$defs/text" },
        "transcript": { "$ref": "#/$defs/text" }
      }
    }
  }
}

=== RR-593/group33/_data/shelves/top.json
{
  "title": "Top shelf",
  "description": "This pelike depicts the use of a mobility aid: a staff or cane. In ancient Greece, staff-like objects were also symbols of power, authority and justice. Archaeological narratives are selective about how these artefacts are interpreted, often rejecting the possibility of disability coinciding with symbols of power.",
  "image": {
    "url": "assets/placeholders/PLACEHOLDER-empty-glass-display-case-modern.jpg",
    "altText": "Object 1. A Pelike. A large Greek-style vase. The scene depicts two men facing each other. One appears to use a staff, possibly as a mobility aid.",
    "caption": "Pelike, MU4759, front view © Gale History Museum"
  },
  "artifacts": [
    {
      "description": "TBC",
      "metaDescription": {
        "name": "Pelike",
        "accNo": "MU4759",
        "material": "Ceramic",
        "dimension": [
          0,
          0,
          0
        ],
        "details": "Painter of Bari 8010, Southern Italy, 350-340 B.C.E. Purchase, 2013"
      },
      "images": [
        {
          "url": "assets/exhibitionShelfs/Top Shelf/Pelike/1 Pelike_MU4759_front_Image1.jpg",
          "altText": "Object 1. A Pelike. A large Greek-style vase. The scene depicts two men facing each other. One appears to use a staff, possibly as a mobility aid.",
          "caption": "Pelike, MU4759, front view © Gale History Museum"
        },
        {
          "url": "assets/exhibitionShelfs/Top Shelf/Pelike/1 Pelike_MU4759_front scene_Image2.jpg",
          "altText": "Object 1. Close-up of the scene on a pelike. A large Greek-style vase. The scene depicts two men facing each other. One appears to use a staff, possibly as a mobility aid.",
          "caption": "Pelike, MU4759, front close-up of scene © Gale History Museum"
        },
        {
          "url": "assets/exhibitionShelfs/Top Shelf/Pelike/1 Pelike_MU4759_back_Image3.jpg",
          "altText": "Object 1. A Pelike. A large Greek-style vase. The scene depicts one seated man and one standing woman facing each other. The woman holds a fan and the man a dish of some sort. Flower-like shapes border the top, scrolls and swirls line the sides, and a Greek key runs along the bottom.",
          "caption": "Pelike, MU4759, back view © Gale History Museum"
        }
      ],
      "audioDescription": {
        "url": "TBC",
        "transcript": "This large ceramic vessel has a wide, thick rim upon a flared neck. A line of leaf-like decorations wraps around the neck. It has one handle on either side, starting below the rim and meeting at the shoulder of the vessel, which becomes a wide, bulbous body upon a circular base. The vessel is black in colour with a light orange scene in the centre. The scene depicts two young men facing each other. Both men are barefoot, have curly hair and wear large toga-style tunics that cover their bodies to the ankle, draping across one shoulder and leaving the other exposed. The man on the left is holding a long staff with his right hand; his arm is bent at the elbow. His right leg is outlined by the fabric and appears to be slightly bent forward, while his right shoulder is facing downwards, as if he is being supported by this staff. The other figure holds a shorter, curved object with his right hand around shoulder height; his arm is bent at the elbow. The two figures are standing on a geometric pattern above the vessel base and are framed by swirling patterns on either side."
      }
    }
  ]
}
